USE [ERMS_Db]
SET IDENTITY_INSERT [dbo].[Employees] ON 
GO
INSERT [dbo].[Employees] ([EmployeeId], [Title], [FirstName], [MiddleName], [LastName], [DateofBirth], [CountryofBirth], [Gender], [MaritalStatus], [DateofMarriage], [PersonalEmail], [ContactNumber], [DateofJoining], [EmployeeCode], [OfficialEmail], [EmployeeTypeId], [RevisedLocationId], [Designation], [OverallExperience], [Skill_Id], [ReportingManagerId], [HighestEducation], [EmploymentStatus], [RelievingDate], [SubPracticeId], [IsEngineering], [IsNextAssignmentIdentified], [NextAssignmentName], [NextAssignmentStartDate], [IsDeleted], [CreatedBy], [ModifiedBy], [CreatedOn], [ModifiedOn]) VALUES (3, N'Mr', N'John', N'Michel', N'Diego', CAST(N'1989-09-23' AS Date), N'USA', N'Male', N'Married', CAST(N'2015-09-23' AS Date), N'diago@gmail.com', N'9878965681', CAST(N'2018-09-23' AS Date), N'NVS000176', N'diego@newvision-software.com', 1, 1, N'Tech Lead', CAST(10.50 AS Decimal(5, 2)), 2, 2, N'BE', 1, NULL, 1, 1, NULL, NULL, CAST(N'1989-09-23' AS Date), 0, 1, 1, NULL, NULL)
GO
INSERT [dbo].[Employees] ([EmployeeId], [Title], [FirstName], [MiddleName], [LastName], [DateofBirth], [CountryofBirth], [Gender], [MaritalStatus], [DateofMarriage], [PersonalEmail], [ContactNumber], [DateofJoining], [EmployeeCode], [OfficialEmail], [EmployeeTypeId], [RevisedLocationId], [Designation], [OverallExperience], [Skill_Id], [ReportingManagerId], [HighestEducation], [EmploymentStatus], [RelievingDate], [SubPracticeId], [IsEngineering], [IsNextAssignmentIdentified], [NextAssignmentName], [NextAssignmentStartDate], [IsDeleted], [CreatedBy], [ModifiedBy], [CreatedOn], [ModifiedOn]) VALUES (4, N'Mr', N'William', N'Steven', N'King', CAST(N'1992-10-02' AS Date), N'Japan', N'Male', N'Unmarried', NULL, N'king@gmail.com', N'9876543218', CAST(N'2022-02-02' AS Date), N'NVS000189', N'king@newvision-software.com', 2, 1, N'Software Developer', CAST(4.50 AS Decimal(5, 2)), 2, 2, N'ME', 1, NULL, 1, 1, NULL, NULL, CAST(N'1989-09-23' AS Date), 0, 1, 1, NULL, NULL)
GO
INSERT [dbo].[Employees] ([EmployeeId], [Title], [FirstName], [MiddleName], [LastName], [DateofBirth], [CountryofBirth], [Gender], [MaritalStatus], [DateofMarriage], [PersonalEmail], [ContactNumber], [DateofJoining], [EmployeeCode], [OfficialEmail], [EmployeeTypeId], [RevisedLocationId], [Designation], [OverallExperience], [Skill_Id], [ReportingManagerId], [HighestEducation], [EmploymentStatus], [RelievingDate], [SubPracticeId], [IsEngineering], [IsNextAssignmentIdentified], [NextAssignmentName], [NextAssignmentStartDate], [IsDeleted], [CreatedBy], [ModifiedBy], [CreatedOn], [ModifiedOn]) VALUES (13, N'Mr', N'Samar', N'Singh', N'Patel', CAST(N'1997-07-15' AS Date), N'USA', N'Male', N'Married', CAST(N'1900-01-01' AS Date), N'Samar@gmail.com', N'75095584  ', CAST(N'2022-07-28' AS Date), N'NVS0012', N'Samar@newvision-software.com', 2, 1, N'Software Engineer', CAST(5.20 AS Decimal(5, 2)), 2, 2, N'B.tech', 1, CAST(N'2022-10-13' AS Date), 1, 1, 0, N'Null', CAST(N'1989-09-23' AS Date), 0, 1, 1, CAST(N'2022-10-13T00:00:00.000' AS DateTime), CAST(N'2022-10-13T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[Employees] ([EmployeeId], [Title], [FirstName], [MiddleName], [LastName], [DateofBirth], [CountryofBirth], [Gender], [MaritalStatus], [DateofMarriage], [PersonalEmail], [ContactNumber], [DateofJoining], [EmployeeCode], [OfficialEmail], [EmployeeTypeId], [RevisedLocationId], [Designation], [OverallExperience], [Skill_Id], [ReportingManagerId], [HighestEducation], [EmploymentStatus], [RelievingDate], [SubPracticeId], [IsEngineering], [IsNextAssignmentIdentified], [NextAssignmentName], [NextAssignmentStartDate], [IsDeleted], [CreatedBy], [ModifiedBy], [CreatedOn], [ModifiedOn]) VALUES (14, N'Mr', N'Vishal', N'Singh', N'Singh', CAST(N'1999-07-15' AS Date), N'India', N'Male', N'married', CAST(N'2015-09-10' AS Date), N'vishal@gmail.com', N'7509558401', CAST(N'2022-07-28' AS Date), N'NVS0013', N'vishal@newvision-software.com', 1, 1, N'Software Engineer', CAST(5.20 AS Decimal(5, 2)), 2, 2, N'BCA', 1, CAST(N'2022-10-13' AS Date), 1, 1, 0, N'Null', CAST(N'1990-09-23' AS Date), 0, 3, 2, CAST(N'2022-10-13T00:00:00.000' AS DateTime), CAST(N'2022-10-13T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[Employees] ([EmployeeId], [Title], [FirstName], [MiddleName], [LastName], [DateofBirth], [CountryofBirth], [Gender], [MaritalStatus], [DateofMarriage], [PersonalEmail], [ContactNumber], [DateofJoining], [EmployeeCode], [OfficialEmail], [EmployeeTypeId], [RevisedLocationId], [Designation], [OverallExperience], [Skill_Id], [ReportingManagerId], [HighestEducation], [EmploymentStatus], [RelievingDate], [SubPracticeId], [IsEngineering], [IsNextAssignmentIdentified], [NextAssignmentName], [NextAssignmentStartDate], [IsDeleted], [CreatedBy], [ModifiedBy], [CreatedOn], [ModifiedOn]) VALUES (16, N'Mr', N'Vishal', N'Singh', N'Singh', CAST(N'1999-07-15' AS Date), N'India', N'Male', N'married', CAST(N'2015-09-10' AS Date), N'vishal@gmail.com', N'7509558401', CAST(N'2022-07-28' AS Date), N'NVS0013', N'vishal@newvision-software.com', 2, 1, N'Software Engineer', CAST(5.20 AS Decimal(5, 2)), 2, 2, N'BCA', 1, CAST(N'2022-10-13' AS Date), 1, 1, 0, N'Null', CAST(N'1990-09-23' AS Date), 0, 1, 0, CAST(N'2022-10-13T00:00:00.000' AS DateTime), CAST(N'2022-10-13T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[Employees] ([EmployeeId], [Title], [FirstName], [MiddleName], [LastName], [DateofBirth], [CountryofBirth], [Gender], [MaritalStatus], [DateofMarriage], [PersonalEmail], [ContactNumber], [DateofJoining], [EmployeeCode], [OfficialEmail], [EmployeeTypeId], [RevisedLocationId], [Designation], [OverallExperience], [Skill_Id], [ReportingManagerId], [HighestEducation], [EmploymentStatus], [RelievingDate], [SubPracticeId], [IsEngineering], [IsNextAssignmentIdentified], [NextAssignmentName], [NextAssignmentStartDate], [IsDeleted], [CreatedBy], [ModifiedBy], [CreatedOn], [ModifiedOn]) VALUES (19, N'Mr', N'Bill', N'Gates', N'Microsoft', CAST(N'1996-07-15' AS Date), N'USA', N'Male', N'Married', CAST(N'2015-09-10' AS Date), N'billgate@gmail.com', N'7509558401', CAST(N'2022-07-28' AS Date), N'NVS0013', N'Billgates@newvision-software.com', 1, 1, N'Engineer', CAST(5.20 AS Decimal(5, 2)), 2, 2, N'B.tech', 1, CAST(N'2022-10-13' AS Date), 1, 1, 0, N'Null', CAST(N'1989-09-23' AS Date), 0, 1, 1, CAST(N'2022-10-13T00:00:00.000' AS DateTime), CAST(N'2022-10-13T00:00:00.000' AS DateTime))
GO
INSERT [dbo].[Employees] ([EmployeeId], [Title], [FirstName], [MiddleName], [LastName], [DateofBirth], [CountryofBirth], [Gender], [MaritalStatus], [DateofMarriage], [PersonalEmail], [ContactNumber], [DateofJoining], [EmployeeCode], [OfficialEmail], [EmployeeTypeId], [RevisedLocationId], [Designation], [OverallExperience], [Skill_Id], [ReportingManagerId], [HighestEducation], [EmploymentStatus], [RelievingDate], [SubPracticeId], [IsEngineering], [IsNextAssignmentIdentified], [NextAssignmentName], [NextAssignmentStartDate], [IsDeleted], [CreatedBy], [ModifiedBy], [CreatedOn], [ModifiedOn]) VALUES (20, N'Mr', N'Vishal', N'Singh', N'Thakur', CAST(N'1990-07-15' AS Date), N'IND', N'Male', N'married', CAST(N'2022-09-10' AS Date), N'Vishal@gmail.com', N'7509558409', CAST(N'2022-07-28' AS Date), N'NVS0012', N'Vishal@newvision-software.com', 1, 1, N'Software Engineer', CAST(4.20 AS Decimal(5, 2)), 2, 2, N'B.tech', 1, CAST(N'2022-10-13' AS Date), 1, 1, 0, N'Null', CAST(N'1986-09-23' AS Date), 0, 1, 0, CAST(N'2022-10-13T00:00:00.000' AS DateTime), CAST(N'2022-10-13T00:00:00.000' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Employees] OFF
GO
